### ISSUE TITLE
Please add me (anesabml) to the triagers team

### ISSUE THREAD

**Issue by anesabml** [aio-libs/triagers#10]
**What's your background?**

I have started using python 5 months ago, mostly doing backend development and writing automated scripts. aiohttp interested me because I am very curious to learn more about asynchronous programming In python.

**What's your motivation?**

I want to help build aiohttp and learn more about how aiohttp works under the hood, moreover I want to get involved in the python community.

**Comment by webknjaz** [comment]
Invited. Some of the advices are here: https://github.com/orgs/aio-libs/teams/triagers/discussions/1.

**Comment by anesabml** [comment]
@webknjaz Thank you so much for this opportunity.
