### ISSUE TITLE
Please add me (paulefoe) to the triagers team

### ISSUE THREAD

**Issue by paulefoe** [aio-libs/triagers#11]
**What's your background?**
I've used aiohttp in quite a few production services. I've also had a few small contributions for aiohttp client. I work with python on a daily basis for the last 3 years, mostly doing web development.

**What's your motivation?**
I have an inner curiosity about how things work internally, the other thought that really thrills my mind is the fact that the code that I will write would be useful to many other developers. And finally, I think that's a good place to learn, usually, open source maintainers and contributors are extremely skilled developers, who can point to my errors and shortcomings.

**Comment by webknjaz** [comment]
Invited. Some of the advice is here: https://github.com/orgs/aio-libs/teams/triagers/discussions/1.
