### ISSUE TITLE
Please add me (Hanaasagi) to the triagers team

### ISSUE THREAD

**Issue by Hanaasagi** [aio-libs/triagers#12]
**What's your background?**

I'm a intermediate Python developer, mostly doing web development. I used `aiohttp` in a prod 2 years ago. At that time, I have read the source code and make some pull requests. You can see them in this [link](https://github.com/aio-libs/aiohttp/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3AHanaasagi). Now, I have free time to do something on my own. So, I think it’s a good opportunity to do something worthwhile.

**What's your motivation?**

Learn more about Python `asyncio` ecosystem by dealing issues of `aiohttp`. I've been watching the `aiohttp` for a while now and helped to respond to some issues that I noticed.

**Comment by webknjaz** [comment]
Perfect! I've sent you an invitation to the Triagers team under this org. You should see it in your inbox now.

**Comment by Hanaasagi** [comment]
Thanks!
