### ISSUE TITLE
Please add me (poyea) to the triagers team

### ISSUE THREAD

**Issue by poyea** [aio-libs/triagers#13]
**What's your background?**
I have been a Python developer for quite a while personally and in the open source space. In most cases, I work on the server side or web dev. `aiohttp` and similar projects (and in general `asyncio`) have been helping me a lot in solving some tricky problems effectively.

**What's your motivation?**
I figure out there might be improvement can be made to `aiohttp`, for example. The current implement support the standard basic auth, but it seems to be possible (given `requests` examples) that we make it available for other auths, without many efforts. Before all these, being a triager could be helpful to me and the community.

**Comment by webknjaz** [comment]
Check your email inbox for the invitation.
