### ISSUE TITLE
Please add me (saket13) to the triagers team

### ISSUE THREAD

**Issue by saket13** [aio-libs/triagers#14]
**What's your background?**
I am a Final Year Grad student at IIIT Gwalior, currently working at houzen, UK. I started learning Python in my sophomore years and liked the simplicity it has to offer. With that said, I complete almost 5 years of programming starting right from College projects to writing Production grade applications in Python. I came across aiohttp while exploring the asynchronous side of Python and the optimizations it provides using the concepts of event loops.

**What's your motivation?**
I am looking to learn from the open source community as well as contribute to it and get my hands dirty. I absolutely love the beauty of async nature of Python programs and want to be able to contribute to its async libraries as more as I can do by understanding the internals of these libraries.

**Comment by webknjaz** [comment]
Check your email inbox for the invitation and Happy New Year :) :christmas_tree:

**Comment by saket13** [comment]
@webknjaz Thanks for the prompt acceptance and I could not expect a better gift for this new year ! 
Happy New Year to you too..!!
