### ISSUE TITLE
Please add me @bizzyvinci to the triagers team

### ISSUE THREAD

**Issue by nbne** [aio-libs/triagers#17]
**What's your background?**
I have good experience with python and data stuffs. I use requests often for data scraping and was thinking about using it asynchronously. I don't know much about aiohttp as I just stumbled on it from [pydantic/pydantic](https://github.com/pydantic/pydantic) -> samuelcolvin -> aiohttp

**What's your motivation?**
I wish to contribute more to open source. I usually go through issue and PR pages of repo but the challenge for me is that the code is either too complicated or I noticed that PRs are not merged or reviews from maintainers take too long. I didn't know about triage until now and it solves my barrier for contributing to opensource.

**Comment by bizzyvinci** [comment]
bizzyvinci here. I noticed I wrote the request from another account.

**Comment by webknjaz** [comment]
Hi @bizzyvinci, I've sent an invitation. Some pointers are at https://github.com/orgs/aio-libs/teams/triagers/discussions/1 and https://github.com/aio-libs/aiohttp/issues/4281.
