### ISSUE TITLE
Please add me (wbarnha) to the triagers team

### ISSUE THREAD

**Issue by wbarnha** [aio-libs/triagers#18]
**What's your background?**

I'm a maintainer of the project at https://github.com/faust-streaming/faust and I use projects from `aio-libs` on a daily basis.

**What's your motivation?**

I would like to have some say in how `aiokafka` and related libraries are maintained since it's critical to the work I do. 

I'd also like to bring https://github.com/aio-libs/aiomonitor back to life if possible.

**Comment by webknjaz** [comment]
Invite's in your inbox. As for aiomonitor, you can revive it. You'd need to start by migrating the CI config from Travis to GHA. Look into aiomysql for examples, plus follow the CI changes happening in other projects over time. Sometimes, we introduce new practices that need to be replicated in the rest of the repos. For example, I'm going to start adding https://github.com/marketplace/actions/checkout-python-sdist at some point and it requires certain restructuring of the jobs.
I think, you can ping @Nothing4you and @Dreamsorcerer for CI advice too.
We have a standard way of publishing from CI that you'll see in other GHA setups across the org. If you follow them, I'll provision the appropriate PyPI tokens as secrets in the corresponding envs.
I'm not sure if the RTD integration still works, will probably have to track down @jettify to get access.

**Comment by Dreamsorcerer** [comment]
> Look into aiomysql for examples, plus follow the CI changes happening in other projects over time.

I try to copy new CI changes I've seen in aiohttp-jinja2, so I often use that repo as a reference (as it's a simple, low maintenance library which doesn't need any special casing).
