### ISSUE TITLE
Please add me (Sukooo) to the triagers team

### ISSUE THREAD

**Issue by Sukooo** [aio-libs/triagers#19]
**What's your background?**

Everything. Already wrotte wrappers with it!

**What's your motivation?**

I am motivated to help this repository develop further.

**Comment by webknjaz** [comment]
Hi, could you be more specific in what you want this for?

**Comment by Sukooo** [comment]
I just think this team fits me pretty well, and I will be able to help the team in different perspectives.

**Comment by webknjaz** [comment]
Can you elaborate in more detail?
