### ISSUE TITLE
Please add me (guidiandrea) to the triagers team

### ISSUE THREAD

**Issue by snapex1** [aio-libs/triagers#22]
**What's your background?**
My background is in electronics and control systems. I started programming with Python in 2018 but I had prior exposure to several programming languages. 

I've used aiohttp as an async replacement for requests given that my project required majority of the code to be async-compatible. 
I consider myself to be a good Python programmer, recently I have also started working with socket programming for fun and also for understanding more of what's under the hood. 
**What's your motivation?**

I want to help because I feel like it's a way to help the community, but also to keep improving and learning new things. 
I expect to learn and to have fun (and hopefully to solve issues :D)

**Comment by Dreamsorcerer** [comment]
Sorry for the delay, invitation sent. Some pointers are at https://github.com/orgs/aio-libs/teams/triagers/discussions/1 and https://github.com/aio-libs/aiohttp/issues/4281.
