### ISSUE TITLE
Please add me (steverep) to the triagers team

### ISSUE THREAD

**Issue by steverep** [aio-libs/triagers#27]
**What's your background?**

I'm a long-time contributor to and member of the Home Assistant team, mainly as a top contributor to the Typescript frontend.  My work mainly focuses on accessibility and performance.  The latter has led me to sever fixes and improvements to `aiohttp`.  My educational background is in aerospace engineering, and my career specialty has always been focused on high performance computing, software development, etc.

**What's your motivation?**

Keep `aiohttp` updated, secure, and as performant as possible since it is an integral part of Home Assistant.  My contributions on `aiohttp` thus far have focused on static file handling and compression.  I plan to implement Brotli compression and possibly Z-Standard as well in the near future.

**Comment by Dreamsorcerer** [comment]
Done
