### ISSUE TITLE
Please add me (Cycloctane) to the triagers team

### ISSUE THREAD

**Issue by Cycloctane** [aio-libs/triagers#28]
**What's your background?**

I started learning asyncio and python web deveploment about two years ago. I use aiohttp and aiomysql to write scripts as well as simple web application backends. I also have experience building backends with other libraries such as flask, starlette and sqlalchemy.

**What's your motivation?**

I want to contribute to opensource software development, especially to those library I've used a lot (like aiomysql and aiohttp). I feel like joining the triagers team can be my first step to give back to opensource community. It's also an opportunity for me to learn new things and get more familiar with python asyncio.

**Comment by webknjaz** [comment]
Invited.
