### ISSUE TITLE
Please add me (lmmx) to the triagers team

### ISSUE THREAD

**Issue by lmmx** [aio-libs/triagers#29]
**What's your background?**

I've used asyncio and the aio* stable for a while, including contributing to the aiohttp-demos repo recently

**What's your motivation?**

I'm happy to help triage issues and maybe work on a GitHub Project kanban board to help visualise it? :smiley_cat:

**Comment by asvetlov** [comment]
I'd sent the invite.

**Comment by webknjaz** [comment]
@lmmx don't forget to accept that invitation within a week, it'll expire otherwise. Closing since the invitation has been sent already.
