### ISSUE TITLE
Please add (atomsforpeace) me at to the triagers team

### ISSUE THREAD

**Issue by AtomsForPeace** [aio-libs/triagers#3]
**What's your background?**
Hi, I'm a Python developer and have been for 5 years. I'm a big fan of async python including a few aio-libs packages. Became maintainer of aiosparql recently, much smaller in comparison. But uses aiohttp.

**What's your motivation?**
I want to help out and try fix issues where I can. I want to get more familiar with how the aiohttp works as it's quite multi-faceted. I've found the people here so far very nice in the gitter/discourse.

**Comment by webknjaz** [comment]
Invitation's in your email.
