### ISSUE TITLE
Please add me (ElusiveSpirit) to the triagers team

### ISSUE THREAD

**Issue by ElusiveSpirit** [aio-libs/triagers#4]
**What's your background?**
Hi, I'm using python for several years in backend development for production and pet projects. Met aiohttp project about 1.5 years ago. Steel using it in production.
Have a team-lead and reviewing experience in a small team.

**What's your motivation?**
I understand, that I'm ready now to share my knowledge with others and contribute open-source, supporting many junior and senior programmers. AioHTTP is a primary tool in my case, so I want it to grow faster.

**Comment by webknjaz** [comment]
Granted.
