### ISSUE TITLE
Please add me (borysvorona) to the triagers team

### ISSUE THREAD

**Issue by borysvorona** [aio-libs/triagers#5]
**What's your background?**
I am a Python Software Engineer with more than 3 years of experience.
Worked with Apache Kafka, Apache Spark, and  WEB frameworks such as aiohttp, Django, Flask, Sanic.
Successful practical experience in REST API, basically using the Django Rest Framework.
Hands-on experience in the development and implementation of a huge medical ERP system that really now is working in Ukraine and can handle over ten thousand active online users.

I think that aiohttp is a simple and self-sufficient python async web framework with a full client and server, as well as sockets under the hood. It has also middleware and other "must-have" toolkits for e-commerce ready python framework.

**What's your motivation?**
I want to join the development team of this awesome framework in order to speed up project development and increase stability. And I also want the community of this product to grow and develop.

**Comment by webknjaz** [comment]
Added to triggers.
