### ISSUE TITLE
Please add me (WisdomPill) to the triagers team

### ISSUE THREAD

**Issue by WisdomPill** [aio-libs/triagers#6]
**What's your background?**

I opened some issues and PRs to the project, I have a basic understanding of the design of the applications using `aiohttp`. I also have experience with protocols, transports and streams using `asyncio`. I developed some services in at my workplace leveraging asyncio and aiohttp. I have 4 years experience in python, mostly `django`, `celery`, scripting and computer vision software using `opencv`. I entered the world of open source actively (committing code) recently, with `aiohttp` and `django_redis`.

**What's your motivation?**

I started playing with `asyncio` and using `aiohttp` in some cases at my workplace, because I do not like how threads are treated in python, I do not like looping indefinitely to check for changes and I do not like taking too much resources for I/O bound applications. `Aiohttp` and `asyncio` are a good choice in my opinion for network applications. I like `aiohttp` because it is more pythonic than tornado and twisted, with which I had experience in the past. I plan on using `aiohttp` more often since I find it easy and elegant to use. I did not play with the other aio-libs although I am interested in `aioredis` and `aiopg`.

**Comment by webknjaz** [comment]
Invited.
