### ISSUE TITLE
Please add me (WolframAlph) to the triagers team

### ISSUE THREAD

**Issue by WolframAlph** [aio-libs/triagers#7]
**What's your background?**
I have been using python for almost 3 years (almost 2 years in commercial development) from now. Mostly to develop REST APIs using Flask framework.

**What's your motivation?**

I am very interested in asynchronous part of python language and I would like to master it better by helping and contributing to such libraries as aiohttp.

**Comment by webknjaz** [comment]
Invitation sent. Check your email.

**Comment by webknjaz** [comment]
Ref: https://github.com/orgs/aio-libs/teams/triagers/discussions/1
